config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root to: "restaurants#index"

  resources :restaurants do
    resources :reviews do
      resources :endorsements, shallow: true
    end
  end

end

app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  validates :name, length: {minimum: 3}, uniqueness: true
  belongs_to :user

  def build_review (current_user, review_params)
      review = Review.new(review_params)
      review.user_id = current_user.id
      review.restaurant_id = self.id
      review
  end
  def average_rating
    return 'N/A' if reviews.none?
    reviews.average(:rating)
  end
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  has_many :endorsements, dependent: :destroy
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "You have already reviewed this restaurant" }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :restaurant
  has_many :reviews
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      # user.name = auth.info.name   # assuming the user model has a name
      # user.image = auth.info.image # assuming the user model has an image
    end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def has_reviewed?(restaurant)
  reviewed_restaurants.include? restaurant
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController
  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
    render json: { new_endorsement_count: @review.endorsements.count }
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_user.restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurants_path
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)

    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end

  def restaurant_params
    params.require(:restaurant).permit(:name)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
  @restaurant = Restaurant.find(params[:restaurant_id])
  @review = @restaurant.build_review current_user, review_params

  if @review.save
    redirect_to restaurants_path
  else
    if @review.errors[:user]
      # Note: if you have correctly disabled the review button where appropriate,
      # this should never happen...
      redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
    else
      # Why would we render new again?  What else could cause an error?
      render :new
    end
  end
end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

  def destroy
    @review = Review.find(params[:id])
    if current_user.id == @review.user_id
      @review.destroy
      flash[:notice] = 'You have successfully deleted your review'
      redirect_to '/restaurants'
    else
      flash[:notice] = 'You can only delete your own reviews'
      redirect_to '/restaurants'
    end
  end

  
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
      # You need to implement the method below in your model (e.g. app/models/user.rb)
      @user = User.from_omniauth(request.env["omniauth.auth"])

      if @user.persisted?
        sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
        set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
      else
        session["devise.facebook_data"] = request.env["omniauth.auth"]
        redirect_to new_user_registration_url
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    # does the rating respond to `round`? If not, just return the rating
    return rating unless rating.respond_to?(:round)

    # if it does – i.e. if it's a valid number - then the rest of the
    # method is run
    remainder = (5 - rating)
    "★" * rating.round + "☆" * remainder
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta charset="UTF-8">
</head>
<body>

<%= notice %>
<%= yield %>

<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to "Sign in", new_user_session_path %>
  <%= link_to "Sign up", new_user_registration_path %>
<% end %>

<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>



</body>
</html>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/restaurants/edit.html.erb
<%= render "form" %>

app/views/restaurants/index.html.erb
<% if @restaurants.any? %>
  <% @restaurants.each do |restaurant| %>
    <h2><%= restaurant.name %></h2>
  <% if restaurant.reviews.any? %>
    <ul>
     <% restaurant.reviews.each do |review| %>
      <li>
       <%= review.thoughts %>, <strong><%= review.rating %></strong>/5
       <%= link_to "Endorse #{restaurant.name}", restaurant_review_endorsements_path(restaurant, review), class: 'endorsements-link' %>
       <span class='endorsements_count'> <%= review.endorsements.count %> </span> <%= 'endorsement'.pluralize(review.endorsements.count) %>
       <%= link_to "Delete Review", restaurant_review_path(restaurant, review), method: :delete %>
    </li>
  <% end %>
    </ul>
<% else %>
 <p>No reviews.</p>
<% end %>
    <%= link_to restaurant.name, restaurant_path(restaurant) %>
    <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>
    <h3>Average rating: <%= star_rating(restaurant.average_rating) %></h3>
    <% if current_user %>
      <% if current_user.id == restaurant.user_id %>
        <%= link_to "Edit #{restaurant.name}", edit_restaurant_path(restaurant) %>
        <%= link_to "Delete #{restaurant.name}", restaurant_path(restaurant), method: :delete %>
      <% end %>
    <% end %>
  <% end %>
<% else %>
  <h1>No restaurants yet</h1>
<% end %>





<!-- <a href='restaurants_path'>Add a restaurant</a> -->
<%= link_to 'Add a restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= render "form" %>
<% if @restaurant.errors.any? %>
  <section id="errors" >
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>

app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>